# Optional URL Rewrite resources: disabled by default
[rewrite_remote]

https://raw.githubusercontent.com/locksherneo/quantumultx-sukka-rules/main/rules/rewrite/reject-url-regex.snippet, tag=SUKKA-REWRITE-reject-url-regex, update-interval=86400, enabled=false
https://raw.githubusercontent.com/locksherneo/quantumultx-sukka-rules/main/rules/rewrite/reject.snippet, tag=SUKKA-REWRITE-reject, update-interval=86400, enabled=false
